Task4 collections
egdeliya/Scala-complete-course pull request #4
Opened 2018-10-10 12:14 UTC by egdeliya

2018-10-10 14:51 UTC, snwlnx requested changes

2018-10-10 14:51 UTC, aliksz commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    if (connection.nonEmpty) connection.get
get на option вызывать не очень хорошо, есть getOrElse

2018-10-10 14:51 UTC, aliksz commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    def mergeAcc(curLeft: Int, curRight: Int, acc: Seq[Int]): Seq[Int] = {
попробуй переписать этом метод с использованием паттерн матчинга, 
и желательно избавиться от acc

2018-10-11 07:20 UTC, snwlnx commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    if (resource.nonEmpty) resource.orNull
```resource.getOrElse(throw new ResourceException)```

2018-10-11 15:45 UTC, egdeliya commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    if (resource.nonEmpty) resource.orNull
Аааа, спасибо:))

2018-10-14 19:41 UTC, snwlnx requested changes
чуток поправить надо

2018-10-14 19:41 UTC, aliksz commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  def mergeSort(data: Seq[Int]): Seq[Int] = {
лучше методы одинаково не называть

2018-10-14 19:41 UTC, aliksz commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    if (connection.nonEmpty) connection.orNull
это конструкция тоже самое, что getOrElse или fold

2018-10-14 19:41 UTC, aliksz commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    mergeSort(0, data.size, data)
какой будет результат 

mergeSort(Vector(1,4,5,6,7,8,9))?

2018-10-14 20:40 UTC, snwlnx approved these changes

2018-10-14 20:40 UTC, aliksz commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case (leftHead +: leftTail, rightHead +: rightTail) =>
обычно в паттерне для листов пишут кратко 
x+:xs y+:ys z+:zs
так привычно легче читается и короче

2018-10-14 20:40 UTC, merged